### ISSUE TITLE
Support for Symfony 6 and php 8.1

### ISSUE THREAD

**Issue by madmortigan1** [php-enqueue/async-command#2]
Hello,

Will there be an update to be able to upgrade to Symfony 6 with PHP 8.1 ?

Thank you

**Comment by makasim** [comment]
Eventually, once someone works on a PR

**Comment by jusmark123** [comment]
So when exactly will that be?

**Comment by makasim** [comment]
@jusmark123 never, since no one is working on it.

**Comment by makasim** [comment]
well, actually it is not quite true. It was added in https://github.com/php-enqueue/enqueue-dev/pull/1239
